/*Generated by orm 2022-01-31 00:56:48, from sqlite3 to sqlite3*/

CREATE TABLE IF NOT EXISTS `test_dump_struct` (`id` INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, `name` TEXT NULL, `is_man` INTEGER NULL, `created` DATETIME NULL);
INSERT INTO `test_dump_struct` (`id`, `name`, `is_man`, `created`) VALUES (1,'1',1,'2022-01-30T19:26:48Z');
INSERT INTO `test_dump_struct` (`id`, `name`, `is_man`, `created`) VALUES (2,'2' || X'0a',0,'2022-01-30T19:26:48Z');
INSERT INTO `test_dump_struct` (`id`, `name`, `is_man`, `created`) VALUES (3,'3;',0,'2022-01-30T19:26:48Z');
INSERT INTO `test_dump_struct` (`id`, `name`, `is_man`, `created`) VALUES (4,'4' || X'0a' || ';' || X'0a' || '''''',0,'2022-01-30T19:26:48Z');
INSERT INTO `test_dump_struct` (`id`, `name`, `is_man`, `created`) VALUES (5,'5''' || X'0a',0,'2022-01-30T19:26:48Z');
