// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// DbmUIClient is the client API for DbmUI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DbmUIClient interface {
	// ListDatabaseSpecs returns a list of Database(s) that can be started through the UI.
	ListDatabaseSpecs(ctx context.Context, in *ListDatabaseSpecsRequest, opts ...grpc.CallOption) (DbmUI_ListDatabaseSpecsClient, error)
	// IsReadOnly returns true if the UI is readonly.
	IsReadOnly(ctx context.Context, in *IsReadOnlyRequest, opts ...grpc.CallOption) (*IsReadOnlyResponse, error)
}

type dbmUIClient struct {
	cc grpc.ClientConnInterface
}

func NewDbmUIClient(cc grpc.ClientConnInterface) DbmUIClient {
	return &dbmUIClient{cc}
}

func (c *dbmUIClient) ListDatabaseSpecs(ctx context.Context, in *ListDatabaseSpecsRequest, opts ...grpc.CallOption) (DbmUI_ListDatabaseSpecsClient, error) {
	stream, err := c.cc.NewStream(ctx, &DbmUI_ServiceDesc.Streams[0], "/v1.DbmUI/ListDatabaseSpecs", opts...)
	if err != nil {
		return nil, err
	}
	x := &dbmUIListDatabaseSpecsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type DbmUI_ListDatabaseSpecsClient interface {
	Recv() (*ListDatabaseSpecsResponse, error)
	grpc.ClientStream
}

type dbmUIListDatabaseSpecsClient struct {
	grpc.ClientStream
}

func (x *dbmUIListDatabaseSpecsClient) Recv() (*ListDatabaseSpecsResponse, error) {
	m := new(ListDatabaseSpecsResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *dbmUIClient) IsReadOnly(ctx context.Context, in *IsReadOnlyRequest, opts ...grpc.CallOption) (*IsReadOnlyResponse, error) {
	out := new(IsReadOnlyResponse)
	err := c.cc.Invoke(ctx, "/v1.DbmUI/IsReadOnly", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DbmUIServer is the server API for DbmUI service.
// All implementations must embed UnimplementedDbmUIServer
// for forward compatibility
type DbmUIServer interface {
	// ListDatabaseSpecs returns a list of Database(s) that can be started through the UI.
	ListDatabaseSpecs(*ListDatabaseSpecsRequest, DbmUI_ListDatabaseSpecsServer) error
	// IsReadOnly returns true if the UI is readonly.
	IsReadOnly(context.Context, *IsReadOnlyRequest) (*IsReadOnlyResponse, error)
	mustEmbedUnimplementedDbmUIServer()
}

// UnimplementedDbmUIServer must be embedded to have forward compatible implementations.
type UnimplementedDbmUIServer struct {
}

func (UnimplementedDbmUIServer) ListDatabaseSpecs(*ListDatabaseSpecsRequest, DbmUI_ListDatabaseSpecsServer) error {
	return status.Errorf(codes.Unimplemented, "method ListDatabaseSpecs not implemented")
}
func (UnimplementedDbmUIServer) IsReadOnly(context.Context, *IsReadOnlyRequest) (*IsReadOnlyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IsReadOnly not implemented")
}
func (UnimplementedDbmUIServer) mustEmbedUnimplementedDbmUIServer() {}

// UnsafeDbmUIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DbmUIServer will
// result in compilation errors.
type UnsafeDbmUIServer interface {
	mustEmbedUnimplementedDbmUIServer()
}

func RegisterDbmUIServer(s grpc.ServiceRegistrar, srv DbmUIServer) {
	s.RegisterService(&DbmUI_ServiceDesc, srv)
}

func _DbmUI_ListDatabaseSpecs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ListDatabaseSpecsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DbmUIServer).ListDatabaseSpecs(m, &dbmUIListDatabaseSpecsServer{stream})
}

type DbmUI_ListDatabaseSpecsServer interface {
	Send(*ListDatabaseSpecsResponse) error
	grpc.ServerStream
}

type dbmUIListDatabaseSpecsServer struct {
	grpc.ServerStream
}

func (x *dbmUIListDatabaseSpecsServer) Send(m *ListDatabaseSpecsResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _DbmUI_IsReadOnly_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IsReadOnlyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DbmUIServer).IsReadOnly(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.DbmUI/IsReadOnly",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DbmUIServer).IsReadOnly(ctx, req.(*IsReadOnlyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DbmUI_ServiceDesc is the grpc.ServiceDesc for DbmUI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DbmUI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "v1.DbmUI",
	HandlerType: (*DbmUIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "IsReadOnly",
			Handler:    _DbmUI_IsReadOnly_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ListDatabaseSpecs",
			Handler:       _DbmUI_ListDatabaseSpecs_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "dbm-ui.proto",
}
